# Generated by Django 3.0.7 on 2020-07-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateField(auto_now_add=True, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='A label for URL config', max_length=63, unique_for_month='pub_date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='startups',
            field=models.ManyToManyField(related_name='blog_posts', to='organizer.Startup'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='blog_posts', to='organizer.Tag'),
        ),
    ]
